### ISSUE TITLE
Failed to connect, return code -1

### ISSUE THREAD

**Issue by Jama13** [8cH9azbsFifZ/pac-n90-raspi#1]
I put the IP address of the broker in pac-n90.c but I keep getting the above error message from the . The broker works and I tested it thoroughly. I tried 127.0.0.1, 127.0.0.1:1883, 192.168.0.11, 192.168.0.11:1883 and without any IP. Nothing seems to be working for me.
Any help with this will be greatly appreciated. Thank you

#if !defined MQTT_ADDRESS
#define MQTT_ADDRESS           "127.0.0.1"  // Address of the mqtt broker
#endif

pi@raspberrypi:~ $ sudo systemctl start pac-n90.service 
pi@raspberrypi:~ $ systemctl status pac-n90.service 
● pac-n90.service - PAC N90 MQTT service.
   Loaded: loaded (/etc/systemd/system/pac-n90.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-06-27 16:55:38 BST; 10s ago
  Process: 25295 ExecStart=/usr/local/bin/pac-n90 (code=exited, status=255/EXCEPTION)
 Main PID: 25295 (code=exited, status=255/EXCEPTION)

Jun 27 16:55:37 raspberrypi systemd[1]: Started PAC N90 MQTT service..
Jun 27 16:55:38 raspberrypi pac-n90[25295]: Failed to connect, return code -1
Jun 27 16:55:38 raspberrypi systemd[1]: pac-n90.service: Main process exited, code=exited, status=255/EXCEPTION
Jun 27 16:55:38 raspberrypi systemd[1]: pac-n90.service: Failed with result 'exit-code'.

**Comment by 8cH9azbsFifZ** [comment]
This sounds like a configuration issue. Just to be sure: you have re-compiled the sources after the change, there is not firewall configured on the MQTT server, and no username/password required?
